### ISSUE TITLE
SEO blocked

### ISSUE THREAD

**Issue by mascam97** [anfepar/anfepar#9]
If I search on internet [anfepar](https://www.google.com/search?q=anfepar) I look your social networks, platzi account and this website.
This website is not tracked by robots due to robots.txt, I do not know if it is a mistake but It could be taken into account.
![Capture](https://user-images.githubusercontent.com/44913087/110191373-95454c80-7ded-11eb-9cf9-def03c11370c.PNG)

**Comment by anfepar** [comment]
Solved :rocket: thanks for your report !
